In [8]:
import torch
import numpy as np

In [11]:
x = torch.empty(5, 3)
print(x)

tensor([[ 0.0000e+00, -1.0842e-19,  0.0000e+00],
        [-1.0842e-19,  1.6816e-44,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 3.6013e-43,  7.7052e+31,  7.2148e+22],
        [ 2.5226e-18,  2.5930e-09,  1.0470e-11]])


In [12]:
x = torch.rand(5, 3)
print(x)

tensor([[0.7201, 0.4765, 0.3826],
        [0.6646, 0.7707, 0.8415],
        [0.1324, 0.9862, 0.0773],
        [0.4552, 0.4084, 0.6883],
        [0.5865, 0.9825, 0.7299]])


In [13]:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [14]:
torch.tensor([1.23, 3])

tensor([1.2300, 3.0000])

In [16]:
x = x.new_ones(5,3, dtype=torch.double)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)


In [17]:
x = torch.randn_like(x,dtype=torch.float)
print(x)

tensor([[ 0.0147,  0.5411, -0.3761],
        [ 1.1027, -0.2807, -1.0168],
        [-1.0604, -1.6342,  2.1118],
        [-0.2263,  0.2578, -1.4636],
        [ 0.4741,  1.6588,  0.7544]])


In [19]:
x = torch.arange(0, 19, 2)
print(x)

tensor([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])


In [22]:
x = torch.linspace(0,3,4)
print(x)

tensor([0., 1., 2., 3.])


In [24]:
x = torch.FloatTensor([5,6,7])
print(x)
print(x.dtype)

tensor([5., 6., 7.])
torch.float32


In [25]:
x = torch.tensor([5,6,7],dtype=torch.int)
print(x.dtype)

torch.int32


In [26]:
torch.manual_seed(42)
x = torch.rand(2,3)
print(x)

tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009]])


In [27]:
x.size()

torch.Size([2, 3])

In [29]:
x.shape

torch.Size([2, 3])

In [30]:
x = torch.rand(5,3)
print(x)

tensor([[0.2566, 0.7936, 0.9408],
        [0.1332, 0.9346, 0.5936],
        [0.8694, 0.5677, 0.7411],
        [0.4294, 0.8854, 0.5739],
        [0.2666, 0.6274, 0.2696]])


In [31]:
y = torch.rand(5,3)
print(y)

tensor([[0.4414, 0.2969, 0.8317],
        [0.1053, 0.2695, 0.3588],
        [0.1994, 0.5472, 0.0062],
        [0.9516, 0.0753, 0.8860],
        [0.5832, 0.3376, 0.8090]])


In [32]:
print(x + y)

tensor([[0.6979, 1.0906, 1.7725],
        [0.2385, 1.2041, 0.9524],
        [1.0688, 1.1149, 0.7473],
        [1.3810, 0.9607, 1.4599],
        [0.8498, 0.9651, 1.0786]])


In [33]:
result = torch.empty(5,3)
torch.add(x,y,out=result)
print(result)

tensor([[0.6979, 1.0906, 1.7725],
        [0.2385, 1.2041, 0.9524],
        [1.0688, 1.1149, 0.7473],
        [1.3810, 0.9607, 1.4599],
        [0.8498, 0.9651, 1.0786]])


In [34]:
y.add_(x)
print(y)

tensor([[0.6979, 1.0906, 1.7725],
        [0.2385, 1.2041, 0.9524],
        [1.0688, 1.1149, 0.7473],
        [1.3810, 0.9607, 1.4599],
        [0.8498, 0.9651, 1.0786]])


In [36]:
print(y[:,1])

tensor([1.0906, 1.2041, 1.1149, 0.9607, 0.9651])


In [37]:
print(y[0,:])

tensor([0.6979, 1.0906, 1.7725])


In [38]:
print(y[2:,1:])

tensor([[1.1149, 0.7473],
        [0.9607, 1.4599],
        [0.9651, 1.0786]])


In [39]:
x = torch.randn(4,4)
y = x.view(16)
z = x.view(-1,8)
print(x.size(),y.size(),z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [40]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([0.5227])
0.5227160453796387


In [41]:
a = torch.ones(3)
print(a)

tensor([1., 1., 1.])


In [42]:
b = a.numpy()
print(b)

[1. 1. 1.]


In [43]:
a.add(3)
print(a)
print(b)

tensor([1., 1., 1.])
[1. 1. 1.]


In [44]:
a = np.ones(3)
print(a)

[1. 1. 1.]


In [45]:
b = torch.from_numpy(a)
print(b)

tensor([1., 1., 1.], dtype=torch.float64)


In [47]:
a = torch.arange(1,4,1,dtype=torch.float)
print(a)

tensor([1., 2., 3.])


In [48]:
a.mean()

tensor(2.)

In [49]:
a.sum()

tensor(6.)

In [50]:
print(a.max())
print(a.min())

tensor(3.)
tensor(1.)


In [51]:
a = torch.tensor([1,2,3],dtype=torch.float)
b = torch.tensor([4,5,6],dtype=torch.float)
print(torch.add(a,b).sum())

tensor(21.)


In [52]:
import math
a = torch.tensor([math.radians(30),math.radians(60),math.radians(90)])

In [53]:
print(torch.sin(a))
print(torch.cos(a))
print(torch.tan(a))
print(torch.asin(a))
print(torch.tanh(a))

tensor([0.5000, 0.8660, 1.0000])
tensor([ 8.6603e-01,  5.0000e-01, -4.3711e-08])
tensor([ 5.7735e-01,  1.7321e+00, -2.2877e+07])
tensor([0.5511,    nan,    nan])
tensor([0.4805, 0.7807, 0.9172])


In [54]:
a = torch.tensor([[1,2,3],[4,5,6]],dtype=torch.float)
b = torch.tensor([[1,2],[3,4],[5,6]],dtype=torch.float)

In [55]:
torch.mm(a,b)

tensor([[22., 28.],
        [49., 64.]])

In [56]:
print(a@b)

tensor([[22., 28.],
        [49., 64.]])
